services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs
    ports:
      - "54321:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
